//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrow
    {
        public Nullable<int> Money { get; set; }
        public string CitizenID { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> MoneyBorrow { get; set; }
        public string KieuTinDung { get; set; }
        public string TaiSanTheChap { get; set; }
        public string KyHan { get; set; }
        public Nullable<System.DateTime> NgayChoVay { get; set; }
        public Nullable<System.DateTime> NgayHoanTien { get; set; }
    }
}
