//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit
    {
        public string STK { get; set; }
        public string MaThe { get; set; }
        public int HanMuc { get; set; }
        public Nullable<int> UsedMoney { get; set; }
        public string Method { get; set; }
        public Nullable<System.DateTime> NgayMo { get; set; }
        public Nullable<System.DateTime> NgayDaoHan { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
